name: GitHub Actions Demo
on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python3 job.py
      - run: echo "Hello depuis la pipeline $(date)" > output.txt
      - run: cat output.txt
